version: "3.2"
services:
  web:
    image: wordpress
    links:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=password
      - WP_DEBUG=false
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - ${PWD}:/var/www/html/wp-content/themes/nextcloud.com

  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=nextcloud
